osx_image: xcode11
language: swift

cache:
- bundler
- cocoapods

before_install:
- cd Example && bundle install

install:
- bundle exec pod install

script:
- cd .. && pod lib lint
- cd Example && bundle exec fastlane test